image: node:alpine

cache:
  - key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

main:
  only:
    - schedules
  script:
    - npm install
    - npm run build
    - npm run start
